server:
    listen: :3000
    title: Muximux
auth:
    method: none
    users: []
    trusted_proxies: []
    headers: {}
    oidc:
        enabled: false
        issuer_url: ""
        client_id: ""
        client_secret: ""
        redirect_url: ""
        scopes: []
        username_claim: ""
        email_claim: ""
        groups_claim: ""
        display_name_claim: ""
        admin_groups: []
    session_max_age: ""
    secure_cookies: false
navigation:
    position: top
    width: 220px
    auto_hide: false
    auto_hide_delay: 3s
    show_on_hover: true
    show_labels: true
    show_logo: false
icons:
    dashboard_icons:
        enabled: true
        mode: on_demand
        cache_dir: data/icons/dashboard
        cache_ttl: 7d
health:
    enabled: true
    interval: 30s
    timeout: 5s
keybindings:
    bindings:
        fullscreen:
            - key: F11
        refresh:
            - key: F5
        search:
            - key: /
            - key: k
              ctrl: true
groups:
    - name: Media
      icon: ""
      color: '#E5A00D'
      order: 0
      expanded: true
    - name: Downloads
      icon: ""
      color: '#00CCFF'
      order: 1
      expanded: true
    - name: System
      icon: ""
      color: '#F46800'
      order: 2
      expanded: true
apps:
    - name: Plex
      url: http://192.0.2.10:32400/web
      icon:
        type: dashboard
        name: plex
        file: ""
        url: ""
        variant: svg
      color: '#E5A00D'
      group: Media
      order: 0
      enabled: true
      default: true
      open_mode: iframe
      proxy: false
      scale: 1
      auth_bypass: []
      access:
        roles: []
        users: []
    - name: Sonarr
      url: http://192.0.2.20:8989
      icon:
        type: dashboard
        name: sonarr
        file: ""
        url: ""
        variant: svg
      color: '#00CCFF'
      group: Downloads
      order: 1
      enabled: true
      default: false
      open_mode: iframe
      proxy: true
      scale: 1
      auth_bypass: []
      access:
        roles: []
        users: []
    - name: Radarr
      url: http://192.0.2.20:7878
      icon:
        type: dashboard
        name: radarr
        file: ""
        url: ""
        variant: svg
      color: '#FFC230'
      group: Downloads
      order: 2
      enabled: true
      default: false
      open_mode: iframe
      proxy: true
      scale: 1
      auth_bypass: []
      access:
        roles: []
        users: []
    - name: Pi-hole
      url: http://192.0.2.100/admin
      icon:
        type: dashboard
        name: pi-hole
        file: ""
        url: ""
        variant: svg
      color: '#96060C'
      group: System
      order: 3
      enabled: true
      default: false
      open_mode: iframe
      proxy: true
      scale: 1
      auth_bypass: []
      access:
        roles: []
        users: []
